name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build the OHCI Image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image-tag: ${{ steps.output-image-tag.outputs.image-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Output image tag
        id: output-image-tag
        # Set the image tag, same used by the isle-gradle-docker-plugin
        run: echo ::set-output name=image-tag::$(git describe --tags --always --first-parent)

      - name: Log in to GHCR
        id: docker_login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: setup buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          pull: false
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/jhu-idc/wait-for-db:latest
            ghcr.io/jhu-idc/wait-for-db:${{ steps.output-image-tag.outputs.image-tag }}
          labels: |
            org.opencontainers.image.source=https://github.com/jhu-idc/oci-wait-for-db
            org.opencontainers.image.title=wait-for-db

